### ISSUE TITLE
API documentation for `transfer` API

### ISSUE THREAD

**Issue by prestonlimlianjie** [netlify/open-api#165]
### Overview of the issue
I'm trying to programmatically create sites on my company's team. However, there doesn't seem to be a way to create team-level access tokens. As such, when I use the JS SDK to create sites, the sites end up on my personal account.

### Attempted solution
I inspected the network calls when I click on the **Transfer Site** button on the Netlify UI, and tried to call the `https://api.netlify.com/api/v1/sites/${SITE_ID}/transfer?account_id=${TEAM_ID}` API to no avail.

Having this API available would really help automate the website creation process for us - I would love to help with this in any way.

**Comment by fool** [comment]
It is fairly likely that there will not anytime soon be an API call you can use to transfer a site between teams;  that's a privileged operation like the rest of account management (creating logins) that we don't intend to allow you to automate at present.

I do have an open feature request for team based access tokens to which I am adding this issue, so we can follow up here if we create that functionality (which I cannot commit our developers to, but which feels somewhat likely to happen, to me), but either way we'll follow up with a response here which you'll get if your GH notifications are setup correctly even though I am closing this issue since as titled, it is WONTFIX.

However, there is a solution to your problem today!  There's an API call to do what you want directly, already:

https://open-api.netlify.com/#/default/createSiteInTeam is the one you want.
